from __future__ import annotations

from datetime import datetime
from html import escape
from io import BytesIO
import re

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
)
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Circle

from .core import ResearchResult, Evidence


class NumberedCanvas(canvas.Canvas):
    """ReportLab canvas that adds headers, footers, and final page counts."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        width, height = A4

        if self._pageNumber > 1:
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#475569"))
            self.drawString(40, height - 35, "ARIA RESEARCH BRIEF")

            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#64748B"))
            self.drawRightString(width - 40, height - 35, "Autonomous Research Intelligence Analyst")

            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(40, height - 42, width - 40, height - 42)

        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(40, 50, width - 40, 50)

        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        self.drawString(40, 35, "Generated by:")
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(100, 35, "ARIA")

        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(width - 40, 35, page_text)

        self.restoreState()


def clean_unsupported_characters(text: str) -> str:
    """Replace common non-ASCII characters that cause black boxes/spots in ReportLab Helvetica."""
    replacements = {
        '\u201c': '"',  # Left double quote
        '\u201d': '"',  # Right double quote
        '\u2018': "'",  # Left single quote
        '\u2019': "'",  # Right single quote
        '\u2014': ' -- ', # Em dash
        '\u2013': '-',   # En dash
        '\u2212': '-',   # Unicode minus sign
        '\u2022': '•',   # Unicode bullet point
        '\u200b': '',    # Zero-width space
        '\u00a0': ' ',   # Non-breaking space
        '\u2011': '-',   # Non-breaking hyphen
    }
    for char, rep in replacements.items():
        text = text.replace(char, rep)
    return text


def clean_markdown_text(text: str, evidence: list[Evidence] | None = None) -> str:
    """Convert a small Markdown subset into ReportLab-safe inline markup."""
    # 1. Clean unsupported characters first
    text = clean_unsupported_characters(text)
    
    # 2. Escape HTML special characters
    text = escape(text)
    
    # 3. Standardize markdown bold, italic, code
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'__(.*?)__', r'<b>\1</b>', text)
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = re.sub(r'_(.*?)_', r'<i>\1</i>', text)
    text = re.sub(
        r'`(.*?)`',
        r'<font name="Courier" size="9" color="#1E293B"><b>\1</b></font>',
        text
    )
    
    # 4. Format citations beautifully as superscripts, removing brackets, with blue links
    if evidence:
        urls = citation_url_map(evidence)
        
        # Standardize punctuation and citations:
        # Move period/comma before the citation and remove spaces:
        text = re.sub(r'\s+([.,;?!])', r'\1', text)
        text = re.sub(r'\s*\[(\d+)\]\s*([.,;?!])', r'\2[\1]', text)
        text = re.sub(r'([.,;?!])\s*\[(\d+)\]', r'\1[\2]', text)
        text = re.sub(r'\s+\[(\d+)\]', r'[\1]', text)
        
        def replace_citation(match: re.Match) -> str:
            number = int(match.group(1))
            if number < 1 or number > len(evidence):
                return match.group(0)
            
            url = urls.get(number)
            if url:
                # Clickable blue superscript number
                return f'<super rise="4.5" size="7"><a href="{escape(url)}"><font color="#2563EB"><b>{number}</b></font></a></super>'
            else:
                # Default grey/slate superscript number
                return f'<super rise="4.5" size="7"><font color="#475569"><b>{number}</b></font></super>'
                
        text = re.sub(r'\[(\d+)\]', replace_citation, text)
        
    return text


def safe_paragraph(text: str, style, bulletText=None) -> Paragraph:
    """Helper to safely build a Paragraph, falling back to clean text on XML parse error."""
    try:
        p = Paragraph(text, style, bulletText=bulletText)
        p.wrap(500, 100)
        return p
    except Exception:
        clean_text = text.replace("<b>", "").replace("</b>", "").replace("<i>", "").replace("</i>", "")
        clean_text = re.sub(r'<[^>]+>', '', clean_text)
        return Paragraph(clean_text, style, bulletText=bulletText)


def confidence_label(result: ResearchResult) -> str:
    """Estimate confidence from evidence volume and source quality."""
    if "NEEDS_MORE_RESEARCH" in (result.verification or "").upper():
        return "Needs Review"
    count = len(result.evidence)
    high_signal = sum(
        1 for item in result.evidence if item.source_type in {"pdf", "research", "finance"}
    )
    if count >= 8 and high_signal >= 2:
        return "High"
    if count >= 4:
        return "Medium"
    if count > 0:
        return "Low-Medium"
    return "Low"


def citation_url_map(evidence: list[Evidence]) -> dict[int, str]:
    return {index: item.url for index, item in enumerate(evidence, start=1) if item.url}


def linkify_citations_markdown(text: str, evidence: list[Evidence]) -> str:
    urls = citation_url_map(evidence)

    def replace(match: re.Match) -> str:
        number = int(match.group(1))
        url = urls.get(number)
        if not url:
            return match.group(0)
        return f"[[{number}]]({url})"

    return re.sub(r"(?<!\!)\[(\d+)\]", replace, text)


SOURCE_COLORS = [
    colors.HexColor("#2563EB"),
    colors.HexColor("#059669"),
    colors.HexColor("#D97706"),
    colors.HexColor("#7C3AED"),
    colors.HexColor("#DC2626"),
    colors.HexColor("#0891B2"),
    colors.HexColor("#475569"),
]


def evidence_type_counts(evidence: list[Evidence]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in evidence:
        source_type = (item.source_type or "unknown").strip().lower() or "unknown"
        counts[source_type] = counts.get(source_type, 0) + 1
    return dict(sorted(counts.items(), key=lambda pair: (-pair[1], pair[0])))


def short_label(value: str | None, max_chars: int) -> str:
    text = " ".join((value or "Untitled source").split())
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3].rstrip() + "..."


def citation_stats(result: ResearchResult) -> dict[str, int]:
    citations = [int(match) for match in re.findall(r"(?<!\!)\[(\d+)\]", result.answer or "")]
    valid = {number for number in citations if 1 <= number <= len(result.evidence)}
    invalid = {number for number in citations if number < 1 or number > len(result.evidence)}
    cited_sources = len(valid)
    total_sources = len(result.evidence)
    return {
        "inline_citations": len(citations),
        "cited_sources": cited_sources,
        "uncited_sources": max(0, total_sources - cited_sources),
        "invalid_citations": len(invalid),
    }


def build_metric_cards(result: ResearchResult, styles) -> Table:
    stats = citation_stats(result)
    metrics = result.metrics or {}
    card_style = ParagraphStyle(
        'MetricCardText',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#64748B"),
        alignment=1,
    )
    value_style = ParagraphStyle(
        'MetricCardValue',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        textColor=colors.HexColor("#0F172A"),
        alignment=1,
    )
    cards = [
        ("Evidence", str(len(result.evidence))),
        ("Citations", str(stats["inline_citations"])),
        ("Iterations", str(metrics.get("iterations", "n/a"))),
        ("Confidence", confidence_label(result)),
    ]
    data = [
        [
            Paragraph(f"<b>{escape(value)}</b>", value_style),
            Paragraph(label, card_style),
        ]
        for label, value in cards
    ]
    table = Table([data], colWidths=[128, 128, 128, 128])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return table


def source_mix_chart(result: ResearchResult) -> Drawing:
    width, height = 250, 128
    drawing = Drawing(width, height)
    counts = evidence_type_counts(result.evidence)
    total = max(1, sum(counts.values()))

    drawing.add(String(0, 116, "Source Mix", fontName="Helvetica-Bold", fontSize=9, fillColor=colors.HexColor("#0F172A")))
    drawing.add(String(0, 102, f"{sum(counts.values())} evidence items across {len(counts)} source types", fontSize=7, fillColor=colors.HexColor("#64748B")))

    x = 0
    bar_y = 82
    bar_width = 230
    items = list(counts.items())
    for index, (source_type, count) in enumerate(items):
        if index == len(items) - 1:
            segment_width = max(0, bar_width - x)
        else:
            segment_width = (count / total) * bar_width
        drawing.add(Rect(x, bar_y, segment_width, 14, fillColor=SOURCE_COLORS[index % len(SOURCE_COLORS)], strokeColor=None))
        x += segment_width
    drawing.add(Rect(0, bar_y, bar_width, 14, fillColor=None, strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=0.5))

    legend_y = 60
    for index, (source_type, count) in enumerate(list(counts.items())[:6]):
        row = index % 3
        col = index // 3
        lx = col * 118
        ly = legend_y - (row * 17)
        pct = round((count / total) * 100)
        drawing.add(Rect(lx, ly, 8, 8, fillColor=SOURCE_COLORS[index % len(SOURCE_COLORS)], strokeColor=None))
        drawing.add(String(lx + 12, ly + 1, f"{source_type.upper()} {count} ({pct}%)", fontSize=7, fillColor=colors.HexColor("#334155")))

    if not counts:
        drawing.add(String(0, 78, "No evidence collected.", fontSize=8, fillColor=colors.HexColor("#64748B")))
    return drawing


def relevance_chart(result: ResearchResult) -> Drawing:
    width, height = 250, 128
    drawing = Drawing(width, height)
    drawing.add(String(0, 116, "Top Source Relevance", fontName="Helvetica-Bold", fontSize=9, fillColor=colors.HexColor("#0F172A")))
    drawing.add(String(0, 102, "Ranked by retrieval/re-ranking score", fontSize=7, fillColor=colors.HexColor("#64748B")))

    top_items = sorted(result.evidence, key=lambda item: item.score, reverse=True)[:5]
    if not top_items:
        drawing.add(String(0, 78, "No relevance scores available.", fontSize=8, fillColor=colors.HexColor("#64748B")))
        return drawing

    max_width = 140
    for index, item in enumerate(top_items):
        y = 82 - (index * 16)
        label = short_label(item.title, 27)
        score = max(0.0, min(1.0, item.score))
        drawing.add(String(0, y + 2, f"{index + 1}. {label}", fontSize=6.8, fillColor=colors.HexColor("#334155")))
        drawing.add(Rect(96, y, max_width, 8, fillColor=colors.HexColor("#E2E8F0"), strokeColor=None))
        drawing.add(Rect(96, y, score * max_width, 8, fillColor=colors.HexColor("#2563EB"), strokeColor=None))
        drawing.add(String(240, y + 1, f"{score:.2f}", fontSize=6.8, fillColor=colors.HexColor("#475569")))
    return drawing


def workflow_timeline(result: ResearchResult) -> Drawing:
    width, height = 515, 72
    drawing = Drawing(width, height)
    stages = ["Plan", "Retrieve", "Draft", "Verify", "Export"]
    stage_x = [36, 146, 256, 366, 476]
    status_color = colors.HexColor("#059669")
    if "NEEDS_MORE_RESEARCH" in (result.verification or "").upper():
        status_color = colors.HexColor("#D97706")

    drawing.add(String(0, 60, "Research Workflow", fontName="Helvetica-Bold", fontSize=9, fillColor=colors.HexColor("#0F172A")))
    drawing.add(Line(stage_x[0], 32, stage_x[-1], 32, strokeColor=colors.HexColor("#CBD5E1"), strokeWidth=1.2))
    for index, stage in enumerate(stages):
        fill = status_color if stage == "Verify" else colors.HexColor("#2563EB")
        drawing.add(Circle(stage_x[index], 32, 10, fillColor=fill, strokeColor=colors.white, strokeWidth=1.2))
        drawing.add(String(stage_x[index] - 6, 29, str(index + 1), fontName="Helvetica-Bold", fontSize=7, fillColor=colors.white))
        drawing.add(String(stage_x[index] - 24, 12, stage, fontSize=7.5, fillColor=colors.HexColor("#334155")))
    return drawing


def citation_coverage_panel(result: ResearchResult, styles) -> Table:
    stats = citation_stats(result)
    total = max(1, len(result.evidence))
    coverage = round((stats["cited_sources"] / total) * 100)
    status = "Passed" if "NEEDS_MORE_RESEARCH" not in (result.verification or "").upper() else "Needs Review"
    rows = [
        ["Inline citations", str(stats["inline_citations"])],
        ["Evidence cited", f"{stats['cited_sources']} of {len(result.evidence)} ({coverage}%)"],
        ["Uncited evidence", str(stats["uncited_sources"])],
        ["Invalid citations blocked", str(stats["invalid_citations"])],
        ["Verification status", status],
    ]
    table = Table(
        [[Paragraph(f"<b>{escape(label)}</b>", styles['Normal']), Paragraph(escape(value), styles['Normal'])] for label, value in rows],
        colWidths=[145, 95],
    )
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return table


def analytics_flowables(result: ResearchResult, styles) -> list:
    return [
        build_metric_cards(result, styles),
        Spacer(1, 8),
        Table(
            [[source_mix_chart(result), relevance_chart(result)]],
            colWidths=[257, 258],
            style=[
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ('PADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ],
        ),
        Spacer(1, 8),
        Table(
            [[workflow_timeline(result), citation_coverage_panel(result, styles)]],
            colWidths=[267, 248],
            style=[
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                ('PADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ],
        ),
    ]


def text_to_flowables(text: str, styles, evidence: list[Evidence] | None = None) -> list:
    """Turn simple Markdown text into ReportLab flowables."""
    flowables = []
    paragraphs = text.split('\n\n')

    subheading_style = ParagraphStyle(
        'SubHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#1E3A8A"),
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    subsubheading_style = ParagraphStyle(
        'SubSubHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )

    bullet_style = ParagraphStyle(
        'BulletList',
        parent=styles['Normal'],
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )

    for para in paragraphs:
        para = para.strip()
        if not para:
            continue

        # Detect code blocks
        if para.startswith('```') and para.endswith('```'):
            code_text = para[3:-3].strip()
            code_style = ParagraphStyle(
                'CodeBlockStyle',
                parent=styles['Normal'],
                fontName='Courier',
                fontSize=8.5,
                leading=12,
                textColor=colors.HexColor("#0F172A")
            )
            # Escape HTML tags inside the code block to prevent formatting issues and replace line breaks
            escaped_code = escape(code_text).replace('\n', '<br/>')
            code_table = Table([[safe_paragraph(escaped_code, code_style)]], colWidths=[515])
            code_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
                ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ('PADDING', (0, 0), (-1, -1), 8),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            flowables.append(code_table)
            flowables.append(Spacer(1, 6))
            continue

        lines = para.split('\n')
        is_bullet_list = all(line.strip().startswith(('-', '*', '+')) for line in lines if line.strip())

        if is_bullet_list:
            for line in lines:
                line_str = line.strip().lstrip('-*+').strip()
                if line_str:
                    flowables.append(safe_paragraph(clean_markdown_text(line_str, evidence), bullet_style, bulletText='•'))
            flowables.append(Spacer(1, 6))
        else:
            if para.startswith('### '):
                header_text = clean_markdown_text(para[4:].strip(), evidence)
                flowables.append(safe_paragraph(header_text, subsubheading_style))
            elif para.startswith('## '):
                header_text = clean_markdown_text(para[3:].strip(), evidence)
                flowables.append(safe_paragraph(header_text, subheading_style))
            else:
                clean_lines = [line.strip() for line in lines if line.strip()]
                clean_para_text = " ".join(clean_lines)
                flowables.append(safe_paragraph(clean_markdown_text(clean_para_text, evidence), styles['BodyText']))
                flowables.append(Spacer(1, 6))

    return flowables


def bold_key_terms(text: str) -> str:
    """Wraps key findings, conclusions, and important terms in markdown bold."""
    import re
    if not text:
        return text
    term_regex = re.compile(
        r"(?<!\*)\b(key findings?|conclusions?|recommendations?|executive summary|in conclusion|overall|most notably|significantly|in summary|successfully)\b(?!\*)",
        re.IGNORECASE
    )
    return term_regex.sub(lambda m: f"**{m.group(0)}**", text)


def build_markdown_report(result: ResearchResult) -> str:
    """Build the downloadable Markdown report."""
    evidence_lines = []
    for index, item in enumerate(result.evidence, start=1):
        title = f"[{item.title}]({item.url})" if item.url else item.title
        provenance = []
        if item.retrieved_via:
            provenance.append(f"retrieved via {item.retrieved_via}")
        if item.source_id:
            provenance.append(f"source id {item.source_id}")
        provenance_text = f" - {'; '.join(provenance)}" if provenance else ""
        evidence_lines.append(f"{index}. **{title}** ({item.source_type}, score {item.score:.2f}){provenance_text}")

    plan_lines = "\n".join(f"- {query}" for query in result.plan)
    evidence_block = "\n".join(evidence_lines) or "No evidence collected."
    confidence = confidence_label(result)

    return f"""# ARIA Research Brief

## Research Question

{result.question}

## Verification Confidence

{confidence}

## Research Plan

{plan_lines}

## Research Brief

{bold_key_terms(linkify_citations_markdown(result.answer, result.evidence))}

## Verification

{result.verification}

## Evidence Register

{evidence_block}
"""


def build_pdf_report(result: ResearchResult) -> bytes:
    """Build the downloadable PDF report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=40,
        rightMargin=40,
        topMargin=50,
        bottomMargin=60
    )

    styles = getSampleStyleSheet()

    styles['Normal'].textColor = colors.HexColor("#334155")
    styles['Normal'].fontSize = 10
    styles['Normal'].leading = 14

    styles['BodyText'].textColor = colors.HexColor("#334155")
    styles['BodyText'].fontSize = 10
    styles['BodyText'].leading = 14

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.white,
        spaceAfter=2
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#94A3B8"),
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )

    metadata_label = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#475569")
    )

    metadata_val = ParagraphStyle(
        'MetaValue',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1E293B")
    )

    bullet_style = ParagraphStyle(
        'BulletList',
        parent=styles['Normal'],
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )

    story = []

    title_data = [
        [
            Paragraph("A R I A", title_style),
            Paragraph("RESEARCH BRIEF", ParagraphStyle(
                'BriefHeading',
                parent=styles['Normal'],
                fontName='Helvetica-Bold',
                fontSize=14,
                leading=18,
                textColor=colors.white,
                alignment=2
            ))
        ],
        [
            Paragraph("Autonomous Research Intelligence Analyst", subtitle_style),
            Paragraph("Generated by ARIA Workspace", ParagraphStyle(
                'BriefSubtitle',
                parent=styles['Normal'],
                fontName='Helvetica',
                fontSize=8,
                leading=10,
                textColor=colors.HexColor("#64748B"),
                alignment=2
            ))
        ]
    ]
    title_table = Table(title_data, colWidths=[300, 215])
    title_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#0F172A")),
        ('PADDING', (0, 0), (-1, -1), 14),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(title_table)
    story.append(Spacer(1, 10))

    confidence = confidence_label(result)
    date_str = datetime.now().strftime("%B %d, %Y")

    metadata_data = [
        [
            Paragraph("<b>Analyst:</b>", metadata_label),
            Paragraph("ARIA", metadata_val),
            Paragraph("<b>Confidence Level:</b>", metadata_label),
            Paragraph(confidence, metadata_val),
        ],
        [
            Paragraph("<b>Date Generated:</b>", metadata_label),
            Paragraph(date_str, metadata_val),
            Paragraph("<b>Evidence Count:</b>", metadata_label),
            Paragraph(f"{len(result.evidence)} Sources Verified", metadata_val),
        ]
    ]
    metadata_table = Table(metadata_data, colWidths=[90, 160, 100, 165])
    metadata_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(metadata_table)
    story.append(Spacer(1, 12))

    question_style = ParagraphStyle(
        'QuestionText',
        parent=styles['Normal'],
        fontName='Helvetica-BoldOblique',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#1E3A8A")
    )
    question_data = [
        [
            Paragraph("<b>RESEARCH OBJECTIVE:</b>", ParagraphStyle('QTitle', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor("#475569"))),
        ],
        [
            safe_paragraph(clean_markdown_text(result.question), question_style)
        ]
    ]
    question_table = Table(question_data, colWidths=[515])
    question_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
        ('BOX', (0, 0), (-1, -1), 1.0, colors.HexColor("#BFDBFE")),
        ('LINELEFT', (0, 0), (-1, -1), 3.0, colors.HexColor("#3B82F6")),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (0, 0), 8),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 10),
    ]))
    story.append(question_table)
    story.append(Spacer(1, 10))

    def add_divider():
        div = Table([[""]], colWidths=[515], rowHeights=[1])
        div.setStyle(TableStyle([
            ('LINEABOVE', (0, 0), (-1, -1), 0.75, colors.HexColor("#E2E8F0")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
        ]))
        return div

    story.append(Paragraph("Research Analytics", section_heading))
    story.append(add_divider())
    story.append(Spacer(1, 6))
    story.extend(analytics_flowables(result, styles))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Research Brief", section_heading))
    story.append(add_divider())
    story.append(Spacer(1, 6))
    story.extend(text_to_flowables(result.answer, styles, result.evidence))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Research Plan", section_heading))
    story.append(add_divider())
    story.append(Spacer(1, 6))
    for query in result.plan:
        query_para = safe_paragraph(f"<i>{clean_markdown_text(query)}</i>", bullet_style, bulletText='•')
        story.append(query_para)
    story.append(Spacer(1, 10))

    if result.verification:
        story.append(Paragraph("Verification", section_heading))
        story.append(add_divider())
        story.append(Spacer(1, 6))
        story.extend(text_to_flowables(result.verification, styles, result.evidence))
        story.append(Spacer(1, 10))

    story.append(Paragraph("Evidence Register", section_heading))
    story.append(add_divider())
    story.append(Spacer(1, 8))

    if result.evidence:
        table_data = [[
            Paragraph("<b>#</b>", ParagraphStyle('TH_Num', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.white)),
            Paragraph("<b>Source Title & Details</b>", ParagraphStyle('TH_Title', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.white)),
            Paragraph("<b>Type</b>", ParagraphStyle('TH_Type', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, textColor=colors.white))
        ]]

        for idx, item in enumerate(result.evidence, start=1):
            if item.url:
                escaped_url = escape(item.url)
                visible_url = item.url
                if len(visible_url) > 75:
                    visible_url = visible_url[:72] + "..."
                escaped_visible_url = escape(visible_url)
                link_str = f'<br/><font color="#3B82F6" size="8">URL: <a href="{escaped_url}">{escaped_visible_url}</a></font>'
            else:
                link_str = ""
            provenance = []
            if item.retrieved_via:
                provenance.append(f"via {item.retrieved_via}")
            if item.source_id:
                provenance.append(f"id {item.source_id}")
            if item.query:
                provenance.append(f"query {item.query}")
            provenance_text = ""
            if provenance:
                provenance_text = f"<br/><font color=\"#64748B\" size=\"8\">{' | '.join(escape(part) for part in provenance)}</font>"
            score_text = f"<br/><font color=\"#64748B\" size=\"8\">Relevance score: {item.score:.2f}</font>"
            title_text = f"<b>{clean_markdown_text(item.title)}</b>{link_str}{score_text}{provenance_text}"

            table_data.append([
                Paragraph(str(idx), ParagraphStyle('TD_Num', parent=styles['Normal'], fontSize=9)),
                safe_paragraph(title_text, ParagraphStyle('TD_Title', parent=styles['Normal'], fontSize=9, leading=12)),
                Paragraph(escape(item.source_type.upper()), ParagraphStyle('TD_Type', parent=styles['Normal'], fontSize=9))
            ])

        evidence_table = Table(table_data, colWidths=[25, 415, 75])

        t_style = [
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
        ]

        for r in range(1, len(table_data)):
            bg_color = colors.HexColor("#F8FAFC") if r % 2 == 1 else colors.white
            t_style.append(('BACKGROUND', (0, r), (-1, r), bg_color))

        evidence_table.setStyle(TableStyle(t_style))
        story.append(KeepTogether([evidence_table]))
    else:
        story.append(Paragraph("<i>No evidence registered.</i>", styles['BodyText']))

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


def build_trace_report(result: ResearchResult) -> str:
    """Build the downloadable markdown research trace and audit log."""
    plan_lines = "\n".join(f"- {query}" for query in result.plan)
    
    # Group evidence by query
    query_evidence: dict[str, list[Evidence]] = {q: [] for q in result.plan}
    unmapped_evidence: list[Evidence] = []
    for item in result.evidence:
        mapped = False
        if item.query:
            # Try to match the query from our plan
            for q in result.plan:
                if item.query == q or q in item.query or item.query in q:
                    query_evidence[q].append(item)
                    mapped = True
                    break
        if not mapped:
            unmapped_evidence.append(item)
            
    # Sub-queries & retrieved sources block
    sources_by_query_lines = []
    for q in result.plan:
        sources_by_query_lines.append(f"### Query: \"{q}\"")
        evs = query_evidence[q]
        if evs:
            for idx, item in enumerate(evs, start=1):
                url_str = f" ({item.url})" if item.url else ""
                tier = getattr(item, "trust_tier", "web")
                sources_by_query_lines.append(
                    f"{idx}. **{item.title}**{url_str}\n"
                    f"   - Trust Tier: `{tier}` | Relevance: `{item.score:.2f}` | Retrieved via: `{item.retrieved_via}`\n"
                    f"   - Snippet: *{item.summary[:200].strip()}...*"
                )
        else:
            sources_by_query_lines.append("*No sources retrieved for this query.*")
        sources_by_query_lines.append("")
        
    if unmapped_evidence:
        sources_by_query_lines.append("### Other / Unmapped Sources")
        for idx, item in enumerate(unmapped_evidence, start=1):
            url_str = f" ({item.url})" if item.url else ""
            tier = getattr(item, "trust_tier", "web")
            sources_by_query_lines.append(
                f"{idx}. **{item.title}**{url_str}\n"
                f"   - Trust Tier: `{tier}` | Relevance: `{item.score:.2f}` | Retrieved via: `{item.retrieved_via}`\n"
                f"   - Snippet: *{item.summary[:200].strip()}...*"
            )
            
    # Parse citations to find used vs discarded
    citations = set(int(m) for m in re.findall(r"(?<!\!)\[(\d+)\]", result.answer or ""))
    used_lines = []
    discarded_lines = []
    
    for idx, item in enumerate(result.evidence, start=1):
        url_str = f" ({item.url})" if item.url else ""
        tier = getattr(item, "trust_tier", "web")
        ev_info = f"- [{idx}] **{item.title}**{url_str}\n  - Trust Tier: `{tier}` | Query: \"{item.query or 'N/A'}\""
        if idx in citations:
            used_lines.append(ev_info)
        else:
            discarded_lines.append(ev_info + "\n  - Discard Reason: Not cited in final synthesized brief.")
            
    used_block = "\n".join(used_lines) or "*No sources were cited in the final brief.*"
    discarded_block = "\n".join(discarded_lines) or "*No sources were discarded.*"
    
    verification_block = result.verification or "No verifier logs available."
    
    return f"""# ARIA Research Trace & Audit Log

## 1. Research Question & Objective

{result.question}

## 2. Planner Stage: Sub-Queries Generated

The lead planner analyzed the research request and generated the following targeted search queries:
{plan_lines}

## 3. Retriever Stage: Sources Retrieved per Query

For each sub-query, the following sources were retrieved:

{"\n".join(sources_by_query_lines)}

## 4. Synthesis Stage: Evidence Usage (Used vs. Discarded)

The synthesizer evaluated each source. Only verified, high-signal sources matching the trust requirements were cited in the final brief.

### Cited / Used Evidence
{used_block}

### Discarded / Unused Evidence
{discarded_block}

## 5. Auditor Stage: Verifier Logs & Grounding Output

Raw verification logs verifying grounding, claim-by-claim confidence scores, and reasoning:

```text
{verification_block}
```
"""

